server:
  port: 8080

spring:
  data:
    mongodb:
      database: ${db.name:kalahdb}
      authentication-database: admin

  jackson:
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE
    serialization.INDENT_OUTPUT: false
    serialization:
      write-dates-as-timestamps: true

my:
  kalah:
    noOfPits: 6
    noOfStones: 6

management:
  server:
    port: 8071
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
